- pom.xml
- src/main/scala/org/apache/spark/sql/pulsar/PulsarConfigurationUtils.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarProvider.scala
- src/test/scala/org/apache/spark/sql/pulsar/PulsarSinkSuite.scala
For connectors, Spark would convert all user-provided parameters in `.option()` as CaseInsensitiveMap, however, pulsar's `loadConf` is case-sensitive.
This PR converts a lowercase key to the key of the exact name.
> Insensitive params convert

- README.md
- src/main/scala/org/apache/spark/sql/pulsar/CachedPulsarClient.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarConfigUpdater.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarMetadataReader.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchReader.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarOptions.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarProvider.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarSource.scala
- src/resources/scalastyle-config.xml
- src/test/scala/org/apache/spark/sql/pulsar/CachedPulsarClientSuite.scala
- src/test/scala/org/apache/spark/sql/pulsar/PulsarTest.scala
This PR attempts to finish the almost-complete authentication for the Pulsar connector. Briefly the following were done:
- `CachedPulsarClient` and `PulsarMetadataReader` sets authentication parameters in the Pulsar clients.
- Auth options in `PulsarOptions` were converted to camel-case, so they can be picked properly by eg. the `AdminUtils.buildAdmin` method.
- A new configuration module type called `pulsar.admin` is added. If given, this configuration is used when creating the admin interface in `PulsarMetaDataReader`. If not, the client configuration will be used.
- Added documentation about the `pulsar.admin` configuration module and some code examples on how to configure authentication when connecting.
During local testing the modified code could authenticate towards to a Pulsar …
> set authentication configuration in Pulsar client (#45)

- pom.xml
- src/main/scala/org/apache/spark/sql/pulsar/AdminUtils.scala
- src/main/scala/org/apache/spark/sql/pulsar/CachedPulsarClient.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarConfigUpdater.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarMetadataReader.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarOptions.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarProvider.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarSinks.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarSources.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarWriteTask.scala
- src/main/scala/org/apache/spark/sql/pulsar/SchemaUtils.scala
User can configure a desired subscription prefix name instead of randomly generated one for reading metadata from pulsar topics.
This change helps user reuse an existing subscription and avoid creating too many random subscriptions during job restarts.
Usage:
```
val s = SparkSession.builder()
.appName("sleep-task")
.getOrCreate()
.readStream
.format("pulsar")
.option("service.url", "pulsar://localhost:6650")
.option("admin.url", "http://localhost:10080")
.option("topic", "public/default/test")
.option("subscriptionprefix", "nlu-test")
.load()
```
Now the subscription can be checked with `stats` command.
```
➜  apache-pulsar-2.8.0 ./bin/pulsar-admin --admin-url "http://localhost:10080"  topics stats public/default/test-partition-1
{
....
"subscriptions" : { …
```
> allow customize the reader subscription prefix

- README.md
- src/main/scala/org/apache/spark/sql/pulsar/PulsarMetadataReader.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarOptions.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarProvider.scala
This PR extends the connector with a boolean parameter (`deserializePayload`), using which users can skip de-serialization if we intend to read topics with multiple different schemas - by just adding an empty schema to the topic and giving back raw values upon de-serialization (that code part could remain unchanged).
**Driving usecase**: we are using the connector for reading DB table change events from Pulsar (using a single topic for a table). Since the data flow is not constant across tables (some of them has a very low inflow, while others might contain high amounts of data) we would like to create a single Spark streaming job for them. This is needed to process this data more efficiently. On the other hand, the connector cannot handle this, since different topics having the DB table …
> feat: allow topics' schemas differ

- src/main/scala/org/apache/spark/sql/pulsar/PulsarMetadataReader.scala
User reported the NPE error for the release 3.1.1.2
```
Traceback (most recent call last):
File "/Users/ashi/MyDev/workspace/src/post_call_etl_job/main_local.py", line 361, in <module>
compute_df = pci.events_queueDF(spark, topic_compute, schema, partition_count)
File "/Users/ashi/MyDev/workspace/src/post_call_etl_job/main_local.py", line 102, in events_queueDF
.option("subscriptionprefix", "nlu-test") \
File "/Users/ashi/MyDev/workspace/.venv/lib/python3.7/site-packages/pyspark/sql/streaming.py", line 482, in load
return self._df(self._jreader.load())
File "/Users/ashi/MyDev/workspace/.venv/lib/python3.7/site-packages/py4j/java_gateway.py", line 1305, in __call__
answer, self.gateway_client, self.target_id, self.name)
File "/Users/ashi/MyDev/workspace/.venv/lib/python3.7/site-packages/pys …
```
> fix getTopics

- src/main/scala/org/apache/spark/sql/pulsar/PulsarDeserializer.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarOptions.scala
- src/main/scala/org/apache/spark/sql/pulsar/SchemaUtils.scala
User needs to access  message properties to decide routing behavior. 
The properties of type Map<String, String> is exposed as MapData[StringType, StringType] in spark sql result.
Example output:
```
+---------+----------+-----+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
|order_uid|product_id|total|               __key|             __topic|         __messageId|       __publishTime|         __eventTime| __messageProperties|
+---------+----------+-----+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
|      105|       500|700.0|[63 61 2D 38 34 3...|persistent://publ...|[08 B5 DF 01 10 1...|2021-11-17 16:49:...|2021-11-17 …
```
> expose pulsar message properties as a metadata column

- src/main/scala/org/apache/spark/sql/pulsar/PulsarSinks.scala
Fix issue #60
Form Spark 3.0.0 a validation is performed when creating Literal. If the string is not of type UTF8String the validation will fail.
The fix is to convert String to UTF8String before creating a string literal.
> Convert String to UTF8String to create string Literal

- src/test/scala/org/apache/spark/sql/pulsar/ConnectorInitializationSuite.scala
This PR adds a test that catches any initialization exceptions during the initialization of the connector.
Specifically, this test was made to provide a reproducable case for issue #92.
> Add connector initialization test

- src/main/scala/org/apache/spark/sql/pulsar/PulsarMetadataReader.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarOffset.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarOptions.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarProvider.scala
Fixes #96
Sometimes we need to specify the start time and end time to pull a batch of data during the period, but currently only the startingtime can be specified.
At the beginning of the program, read through seek to the specified endingtime messageId.
This change is a trivial rework / code cleanup without any test coverage.
*(or)*
This change is already covered by existing tests, such as *(please describe tests)*.
*(or)*
This change added tests and can be verified as follows:
*(example:)*
- *Added integration tests for end-to-end deployment with large payloads (10MB)*
- *Extended integration test for recovery after broker failure*
*If the box was checked, please highlight the changes*
> [FEATURE] Add endingtime feature

- README.md
We publish artifacts into maven central now instead of bintary.
So remove the bintary related documentation.
> remove bintary doc from README

- src/main/scala/org/apache/spark/sql/pulsar/PulsarContinuousReader.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarMetadataReader.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchReader.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarOptions.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarProvider.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarRelation.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarSourceRDD.scala
Fixes #100 
*pulsar allows to configure subscriptionRolePrefix, but pulsar-spark does not configure the subscriptionRolePrefix parameter.*
This change is a trivial rework / code cleanup without any test coverage.
*(or)*
This change is already covered by existing tests, such as *(please describe tests)*.
*(or)*
This change added tests and can be verified as follows:
*(example:)*
- *Added integration tests for end-to-end deployment with large payloads (10MB)*
- *Extended integration test for recovery after broker failure*
Need to update docs? 
(If you need help on updating docs, create a doc issue)
(Please explain why)
(If this PR contains doc changes)
> fix: the subscriptionPrefix parameter does not take effect

- pom.xml
- src/main/scala/org/apache/spark/sql/pulsar/CachedConsumer.scala
- src/main/scala/org/apache/spark/sql/pulsar/CachedPulsarClient.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarHelper.scala
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*
Fixes #<xyz>
*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*
Master Issue: #113 
Reduce the hard dependency on PulsarAadmin as much as possible
Replace all admin calls with the equivalent client or consumer calls:
| admin call | client or consumer call |
| --- | ----------- |
| admin.topics().createSubscription(...) | consumer.subscribe() |
| admin.topics().resetCursor(...)  |  consumer.seek() |
| admin.topics().deleteSubscription(...)  |  consumer.unsubscribe() |
| admin.schemas().getSchemaInfo(...)  |  clientImpl.getSchema(...) |
| admin.topics().getLastMessageId(...)  |  consumer.getLastMessageId |
| admin.topics().getPartitionedTopicMetadata(...)  | …
> [Improve] replace admin calls with client or consumer calls in PulsarHelper

- src/main/scala/org/apache/spark/sql/pulsar/CachedConsumer.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarHelper.scala
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*
Fixes #107 
*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*
Master Issue: #<xyz>
Currently, the connector will create readers with already-used subscription names to set up starting offsets. This causes conflicts and even requires additional permission or subscription work.
1. use the `CachedConsumer` instead of ad-hoc reader to establish initial offsets
This change is a trivial rework / code cleanup without any test coverage.
*(or)*
This change is already covered by existing tests, such as *(please describe tests)*.
*(or)*
This change added tests and can be verified as follows:
*(example:)*
- *Added integration …
> clean initial offset setup

- src/main/scala/org/apache/spark/sql/pulsar/PulsarWriteTask.scala
fix #136 
Currently, producers will stay connected with a broker after each micro-batch, thus causing a broker-side producer spam issue and eventually affecting the broker's performance.
call `producer.close()` when clean up
> close producer during cleanup

- pom.xml
*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*
Shade commonly used library in Uber Jar to avoid conflict.
> Shade common libraries in uber jar to avoid potential dependency conflicts.

- src/main/scala/org/apache/spark/sql/pulsar/PulsarProvider.scala
https://github.com/streamnative/pulsar-spark/issues/37 reported that null pointer exception may be thrown from jsonOptions if there is no active spark session.
Call SparkSession.builder().getOrCreate(). It will look up the thread local spark session, then global session, and create a new session if neither exists.
> Fix the null pointer exception when there is no active session in the current thread.

- pom.xml
1.  the authentication plugin config is full class name, that means we cannot shade these classes.
2. Per: https://jlbp.dev/JLBP-18. We should not shade dependencies proactively.
> stop shading pulsar client and commons

- src/main/scala/org/apache/spark/sql/pulsar/PulsarSourceRDD.scala
When start offset is exclusive and equal to end offset, current code will read past the end, which results in data duplicate.
Reader seek() is redundant inside pulsar RDD(because start offset is already specified for the reader) and sometimes cause data loss(sometimes the cursor forward when seeking the current offset).
Remove redundant reader seek()
Set isLast flag to true if start offset = end offset when start offset is exclusive.
> Fix data duplicate and data loss

- src/main/scala/org/apache/spark/sql/pulsar/PulsarHelper.scala
Fix the 2 bugs in getUserProvidedMessageId
1. consumer.asInstanceOf[ConsumerImpl[GenericRecord]].hasMessageAvailable may throw exception if consumer is freshly started.
2. initial message id is not wrap in UserProvidedMessageId class, which cause the first message to be skipped.
3. when consumer seek() and read() it actually skip the start message if the message is not a batch message
No longer call hasMessageAvailable() method.
Wrap initial offset inside UserProvidedMessageId
change to use reader instead of consumer.
> Fix the issue of getting initial offset with user provided start

- pom.xml
- src/main/scala/org/apache/spark/sql/pulsar/JSONParser.scala
We would like to use pulsar-spark with Spark 3.4.0
Updated pom.xml to Apache Spark 3.4.0 and adjusted TimestampFormatter parameters
> Bump to Spark 3.4.0

- src/test/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchSourceSuite.scala
- src/test/scala/org/apache/spark/sql/pulsar/PulsarSinkSuite.scala
- src/test/scala/org/apache/spark/sql/pulsar/PulsarSourceSuiteBase.scala
- src/test/scala/org/apache/spark/sql/pulsar/PulsarSourceTest.scala
- src/test/scala/org/apache/spark/sql/pulsar/SchemaData.scala
Test build fail after spark dependency upgrade to 3.4
Fix the build failure caused by spark upgrade
> Fix the build failure caused by spark upgrade

- pom.xml
- src/test/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchSourceSuite.scala
Exclude slf4j and log4j library of pulsar dependency because it conflicts with the slf4j and log4j library of spark 3.4
Exclude slf4j and log4j library of pulsar dependency.
> Exclude logging dependency of pulsar library

- src/main/scala/org/apache/spark/sql/pulsar/PulsarSource.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarSources.scala
GetBatch doesn't print offset range correctly because it is not a case class
`2023-08-11T22:57:20.8908016Z stream execution thread for [id = 71ece58b-2fbe-4937-b4ef-d6bfa68aa396, runId = b6efacc4-df39-45b4-958c-e63e13698840]: GetBatch generating RDD of offset range: org.apache.spark.sql.pulsar.PulsarOffsetRange@53a7eb97`
Make offset range a case class so that it can be printed correctly.
> improve logging

- README.md
- src/main/scala/org/apache/spark/sql/pulsar/PulsarHelper.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarOptions.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarProvider.scala
- src/test/scala/org/apache/spark/sql/pulsar/PulsarAdmissionControlSuite.scala
In #151 we added `admin.url` without adding Admin Confs. 
Basically reverting #120 
- [ x] Make sure that the change passes the CI checks.
- [ x] This change is a trivial rework / code cleanup without any test coverage.
> Adding PulsarAdmin configs to PulsarHelper

- src/main/scala/org/apache/spark/sql/pulsar/PulsarHelper.scala
There is a redundant getStats call in Pulsar admin control
Remove the redundant call.
> Remove redundant get Stats call

- src/main/scala/org/apache/spark/sql/pulsar/PulsarClientFactory.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarHelper.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarSinks.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarSource.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarSourceRDD.scala
Previously we used the SparkConf in SparkEnv to get the pulsar client factory class in executor, which is not configurable in driver side.
Propagate the pulsarClientFactoryClassName from driver to executor tasks.
> Propagate pulsar client factory class name from driver spark context to RDD

- README.md
- src/main/scala/org/apache/spark/sql/pulsar/PulsarWriteTask.scala
I wanted to have the ability to add message properties when writing messages to Pulsar.
I have changed the createProjections and sendRow methods in order to correctly serialize the message properties.
Since there are currently no proper tests, it might be worth for someone to take another look at creating them.
In addition, I have mentioned the __messageProperties support in the README.md
> Added message properties serialization to Pulsar write task.

- src/main/scala/org/apache/spark/sql/pulsar/PulsarSource.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarSourceRDD.scala
- src/test/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchSourceSuite.scala
Add input rate metrics to pulsar source to improve observability.
Use accumulator to collect the number of bytes and rows processed in a micobatch.
> Add number of rows and bytes metrics for pulsar source

- README.md
- src/main/scala/org/apache/spark/sql/pulsar/PulsarSources.scala
poolTimeMs should be pollTimeMs
Fix the typo
> fix typo of pollTimeMs

- pom.xml
- src/main/scala/org/apache/spark/sql/pulsar/CachedPulsarClient.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarConfigUpdater.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarDeserializer.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarHelper.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarSerializer.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarSource.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarWriteTask.scala
- src/main/scala/org/apache/spark/sql/pulsar/SchemaUtils.scala
- src/test/scala/org/apache/spark/sql/pulsar/ConnectorInitializationSuite.scala
- src/test/scala/org/apache/spark/sql/pulsar/PulsarMicroBatchSourceSuite.scala
- src/test/scala/org/apache/spark/sql/pulsar/PulsarSinkSuite.scala
- src/test/scala/org/apache/spark/sql/pulsar/PulsarSourceSuiteBase.scala
- src/test/scala/org/apache/spark/sql/pulsar/PulsarTest.scala
- src/test/scala/org/apache/spark/sql/pulsar/SchemaData.scala
*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*
- scala version from 2.12.17 to 2.13.12
- Pulsar version to 2.10.5
- Spark version to 3.4.1
- various scala code to clean warning message
> update scala version to 2.13

- src/main/scala/org/apache/spark/sql/pulsar/PulsarSourceRDD.scala
Currently we don't make sure pulsar reader is closed in all scenarios, only PulsarClientException is handled.
Use task completion iterator to make sure pulsar reader is closed.
> Close pulsar reader in both success and failure case

- pom.xml
- src/main/scala/org/apache/spark/sql/pulsar/PulsarConfigurationUtils.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarHelper.scala
- src/test/scala/org/apache/spark/sql/pulsar/PulsarAdmissionControlSuite.scala
co-authored with @neilramaswamy, who found this bug: https://github.com/streamnative/pulsar-spark/issues/181
*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*
There was a race condition in Pulsar that was surfaced by this issue: https://github.com/apache/pulsar/issues/10671
This is solved in This PR: https://github.com/apache/pulsar/pull/22201 which is present in all Pulsar versions >= 3.0.
Upgrading the Pulsar version from 2.10 to 3.3.2
> Upgrading Pulsar Version to 3.3.2

- pom.xml
BouncyCastle which is a dependency from pulsar client is not shaded.  This can cause conflicts with user libraries that users need to use in their streaming queries.
shade bouncy castle 
> shade bouncy castle so there are no conflicts with user libraries

- src/main/scala/org/apache/spark/sql/pulsar/PulsarOffset.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarSource.scala
- src/main/scala/org/apache/spark/sql/pulsar/PulsarSourceRDD.scala
- src/test/resources/log4j.properties
- src/test/scala/org/apache/spark/sql/pulsar/PulsarSourceSuiteBase.scala
- src/test/scala/org/apache/spark/sql/pulsar/PulsarTest.scala
The seek API has been historical problematic and buggy.  We have seen instances where calling seek to an message id did not actually move the read cursor to the correct message id.  It skipped some messages causing data to be lost.  Lets remove using this problematic API since it is not really needed to beginning with.
Remove using the Seek API and adding additional debugging logs and invariant checking
> Removing using problematic "seek" API and adding additional debug messages

- .github/workflows/release.yml
- pom.xml
> The OSSRH service will reach end-of-life on [June 30th, 2025](https://central.sonatype.org/news/20250326_ossrh_sunset/). Learn more about how to transfer to the Central Publishing Portal [here](https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/#process-to-migrate).
> Migrate nexus staging to nexus central
